// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "practica1.h"

ColaServicio miCola = ColaServicio();
ListaUsuario milista =ListaUsuario();
PilaRecurso miPila = PilaRecurso();
int idses = 0;



std::string  practica1::newrecurso(const recurso& Recurso)
{
	miCola.encolar(Recurso);
	return "Se agrego el recurso exitosamente";
}

std::string  practica1::crearUsuario(const usuariosimple& user)
{
	std::string result ="default";
	usuariosimple Usuario = user;
	std::string dominio = miCola.desencolar().dominio;

	if(dominio.compare("NULL")!=0)
	{
		std::string aux = Usuario.id+"."+ dominio;

		usuario user1;
		user1.id =aux;
		user1.nombre = Usuario.nombre;
		user1.correo = Usuario.correo;
		user1.fecha  = Usuario.fecha;
		user1.dominio= dominio;
		
		result = milista.insertarLista(user1);
	}else
	{
		result="no existen recursos en la cola ";
	}

	return result;

}


getRecurso  practica1::getrecurso(const std::string& id)
{
	getRecurso result;

	idses = idses+50;
	std::string cadena  = std::to_string(idses);

	std::string idSession = "RTX"+cadena;
	std::string idUsuario = id;
	usuario user = milista.getUsuario(idUsuario);
	std::string dominio = user.dominio;

	if(dominio.compare("NULL")!=0)
	{
		recurso r = miCola.buscarDominio(dominio);

		result.idSesion = idSession;
		result.usuario = user.nombre;
		result.dominio = r.dominio;
		result.contenido = r.contenido;
		miPila.push({idSession,idUsuario});
	}else
	{

		result.idSesion = "No existe usario ni recurso asociado a este id";
		result.usuario = "No existe usario ni recurso asociado a este id";
		result.dominio = "No existe usario ni recurso asociado a este id";
		result.contenido = "No existe usario ni recurso asociado a este id";

	}
	return result;
}

 std::list<usuario>   practica1::obtenerUsuarios()
{
	return milista.linealizar();
}

 std::list<recurso> practica1::obtenerCola()
 {
	return miCola.linealizar();
 }

 std::list<servicio1> practica1::obtenerPila()
 {
	return miPila.linealizar(milista);
 }