// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PRACTICA1_H
#define PRACTICA1_H

#include <ngrest/common/Service.h>
#include <string>
#include "NodoCola.h"
#include "Cola.h"
#include "NodoUser.h"
#include "Lista.h"
#include "Pila.h"

struct getRecurso{
        std::string idSesion;
        std::string usuario;
        std::string dominio;
        std::string contenido;
    };

struct usuariosimple
{
    std::string id;
    std::string nombre;
    std::string correo;
    std::string fecha;

};   

//! Dummy"" description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: practica1
class practica1: public ngrest::Service
{
public:
   

    // *method: POST
    // *location: /newrecurso
    std::string  newrecurso(const recurso& Recurso);

    // *method: POST
    // *location: /newuser
    std::string  crearUsuario(const usuariosimple& user);

    // *method: GET
    // *location: /getrecurso/{id}
    getRecurso  getrecurso(const std::string& id);

    // *method: GET
    // *location: /getusuarios
     std::list<usuario> obtenerUsuarios();
     

    // *method: GET
    // *location: /getcolaservicios
     std::list<recurso> obtenerCola();


    // *method: GET
    // *location: /getpila
     std::list<servicio1> obtenerPila();




};



#endif // PRACTICA1_H



